---

- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      apt:
        update_cache: yes
        upgrade: dist        

  roles:
    - mariadb
    - php
    - nginx
    - wordpress
